name: Build, Push Docker Image and Update Manifests

on:
  push:
    branches:
      - release

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      id: build_and_push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: rangadm/salary_calculator:${{ github.run_number }}

    - name: Checkout manifests repository
      uses: actions/checkout@v2
      with:
        repository: RangaDM/Ultimate-CI-CD-Pipeline-manifests
        path: manifests

    - name: Update deployment file with new image tag
      run: |
        sed -i "s|image: rangadm/salary_calculator:.*|image: rangadm/salary_calculator:${{ github.run_number }}|" manifests/deployment.yml
        cd manifests
        git config --global user.email "rangamaithreepala@gmail.com"
        git config --global user.name "RangaDM"
        git add deployment.yml
        git commit -m "Update deployment image to version ${{ github.run_number }}"
        git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/RangaDM/Ultimate-CI-CD-Pipeline-manifests.git HEAD:main
